name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Install Node.js dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- CORREÇÃO FINAL AQUI ---
      - name: Clean install Node.js dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
      # --- FIM DA CORREÇÃO ---

      - name: Build assets with Vite
        run: npm run build

      - name: Execute tests
        run: php artisan test
